### ISSUE TITLE
Enhance the display on input boxes in the Create FLOAT page

### ISSUE THREAD

**Issue by Bamthelearner** [muttoni/float#13]
![image](https://user-images.githubusercontent.com/95492891/153165089-7df7a309-8920-41db-9095-a4bb0a6ef023.png)

It is good to have "100" displayed to demonstrate the format of how people should input to it.
But sometimes confusing if the user can use it as a default number.

Suggested to change it to "e.g. 100"
Similar idea to secret code, can be "e.g. mySecretCode"

Please also remind the FLOAT Creator and Claimers the FLOAT code is case sensitive.

**Comment by jacob-tucker** [comment]
Fixed :)
