### ISSUE TITLE
Make error messages more user-friendly

### ISSUE THREAD

**Issue by jubnzv** [muttoni/float#31]
Hey,

Recently, when claiming a float, the following error often occurs:

![image](https://user-images.githubusercontent.com/12023585/172983661-0266fd9b-5a89-46fc-9e21-abd61eec6aa2.png)

As far as I understand, the problem is that there are not enough tokens on the account that pays transaction fee in the Flow blockchain.

But the problem is that there are some users who can't actually figure out what's going on. I've seen questions like: "Does this message mean, I have to deposit tokens to my Flow wallet?".

Do you think it's worth making this message more user-friendly so as not to scare non-technical users? For example, we could display something like: `We are having technical problems, please try again later`.

**Comment by jacob-tucker** [comment]
I have made these error messages more user friendly. If you encounter any others that look really scary, let me know and I'll fix them right up.

Thank you! :D
