### ISSUE TITLE
Two FLOATs that I can't claim 

### ISSUE THREAD

**Issue by ohmyharry** [muttoni/float#34]
Here are the detail:

https://floats.city/0x66a76313af93e9ee/event/287707085
[Error Code: 1103] The account with address (66a76313af93e9ee) uses 100174 bytes of storage which is over its capacity (100000 bytes). Capacity can be increased by adding FLOW tokens to the account.

https://floats.city/0x78993d7e62c7015f/event/296436406 
[Error Code: 1103] The account with address (78993d7e62c7015f) uses 100350 bytes of storage which is over its capacity (100000 bytes). Capacity can be increased by adding FLOW tokens to the account.

**Comment by brunogonzales** [comment]
I think the account is out of storage capacity. You could increase it by bumping it's Flow balance.

This link might be helpful https://docs.onflow.org/concepts/storage/#storage-capacity
